// scripts/expand_env.cjs
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const coursesPath = path.resolve(__dirname, '../content/courses.js');
const rawCode = fs.readFileSync(coursesPath, 'utf8');

const sandbox = { window: {}, module: { exports: {} } };
vm.runInNewContext(rawCode, sandbox);
const { LXP_CATEGORIES, LXP_COURSES } = sandbox;

console.log('Loaded courses for Environmental:', Object.keys(LXP_COURSES).length);

// -------------------------------------------------------------
// ENVIRONMENTAL & SUSTAINABILITY: Carbon Accounting & ESG (env-m1)
// -------------------------------------------------------------
const envReading = `
> **Industry Alignment & Sustainability Standard**: Aligned with **GHG Protocol** and **ISO 14001 (Environmental Management)**. Essential for ESG Analysts, Environmental Engineers, and Sustainability Officers.

# Corporate Sustainability, ESG, and Carbon Accounting

The transition to a low-carbon economy is no longer just an environmental goal; it is a strict regulatory and financial requirement for modern corporations. Supply chains, industrial operations, and energy procurement are now heavily audited under Environmental, Social, and Governance (ESG) frameworks.

## 1. The GHG Protocol and Scopes
Carbon accounting is the process of calculating a company's total greenhouse gas emissions. The global standard for this is the **Greenhouse Gas (GHG) Protocol**, which categorizes emissions into three scopes:
- **Scope 1 (Direct)**: Emissions from sources that are owned or controlled by the company (e.g., fuel combustion in company vehicles or factory furnaces).
- **Scope 2 (Indirect - Energy)**: Emissions from the generation of purchased electricity, steam, heating, or cooling consumed by the company.
- **Scope 3 (Indirect - Value Chain)**: All other indirect emissions that occur in a company's value chain. This is often the largest source and includes business travel, waste disposal, and the lifecycle emissions of purchased raw materials.

## 2. Life Cycle Assessment (LCA)
Environmental engineers use Life Cycle Assessments to evaluate the environmental impact of a product from "cradle to grave."
- **System Boundary**: The defined limits of the assessment. Does the boundary stop when the product leaves the factory (cradle-to-gate), or does it include consumer use and recycling (cradle-to-grave)?
- **Carbon Footprint**: The total amount of greenhouse gases (expressed in CO2 equivalent) generated by our actions. LCAs pinpoint "hotspots" in the supply chain where redesigning a material can drastically lower the overall carbon footprint.

## 3. Decarbonization Strategies
Once emissions are quantified, companies must implement decarbonization strategies to reach "Net Zero."
- **Energy Efficiency**: Upgrading HVAC systems, insulating facilities, and optimizing industrial processes.
- **Renewable Energy Certificates (RECs)**: Purchasing RECs to offset Scope 2 emissions, proving that a specific amount of electricity was generated from renewable sources.
- **Carbon Offsets**: Investing in external projects (like reforestation or direct air capture) to compensate for emissions that are technically impossible to eliminate today.

---
> **Key Takeaway**: Authentic sustainability requires rigorous data. By applying **Life Cycle Assessments** and strictly categorizing emissions via the **GHG Protocol (Scopes 1-3)**, companies transition from greenwashing to measurable decarbonization.
`;

const envDialogue = {
  title: "ESG Audit: Supply Chain Emissions",
  titleES: "Auditoría ESG: Emisiones en la Cadena de Suministro",
  scenarioContext: "Corporate HQ (Sustainability Office). Preparing the annual ESG report for investors.",
  characters: [
    { name: "Diana Reyes", role: "Chief Sustainability Officer", avatar: "DR", color: "var(--cyan)" },
    { name: "Robert Hill", role: "Supply Chain Manager", avatar: "RH", color: "var(--emerald)" }
  ],
  turns: [
    {
      speaker: "Diana Reyes",
      text: "Robert, our Scope 1 and Scope 2 emissions look solid thanks to the new solar panels at the factory. However, our Scope 3 emissions have spiked by 15% this quarter.",
      translation: "Robert, nuestras emisiones de Alcance 1 y Alcance 2 se ven sólidas gracias a los nuevos paneles solares en la fábrica. Sin embargo, nuestras emisiones de Alcance 3 se han disparado un 15% este trimestre.",
      targetTerms: ["Scope 1", "Scope 2 emissions", "solar panels", "Scope 3 emissions", "spiked"]
    },
    {
      speaker: "Robert Hill",
      text: "I reviewed the Life Cycle Assessment (LCA) data. The spike is coming from upstream logistics. We had to switch to air freight because the maritime shipping lanes were disrupted.",
      translation: "Revisé los datos del Análisis de Ciclo de Vida (LCA). El pico proviene de la logística upstream. Tuvimos que cambiar a flete aéreo porque las rutas de envío marítimo estaban interrumpidas.",
      targetTerms: ["Life Cycle Assessment", "upstream logistics", "air freight", "maritime shipping"]
    },
    {
      speaker: "Diana Reyes",
      text: "We can't let this jeopardize our Net Zero targets. We need a decarbonization strategy for logistics. Have you looked into purchasing verified carbon offsets to mitigate the air freight impact?",
      translation: "No podemos dejar que esto ponga en peligro nuestros objetivos Net Zero. Necesitamos una estrategia de descarbonización para la logística. ¿Has considerado comprar compensaciones de carbono (carbon offsets) verificadas para mitigar el impacto del flete aéreo?",
      targetTerms: ["Net Zero targets", "decarbonization strategy", "verified carbon offsets", "mitigate"]
    },
    {
      speaker: "Robert Hill",
      text: "Yes, but offsets are getting expensive. A better long-term solution is to source raw materials from local suppliers. That shrinks our system boundary and drastically reduces transport emissions.",
      translation: "Sí, pero las compensaciones se están encareciendo. Una mejor solución a largo plazo es obtener materias primas de proveedores locales. Eso reduce nuestro límite de sistema (system boundary) y reduce drásticamente las emisiones de transporte.",
      targetTerms: ["long-term solution", "raw materials", "system boundary", "transport emissions"]
    }
  ],
  contrastTips: [
    {
      school: "The factory's smoke is polluting.",
      native: "The factory's Scope 1 emissions must be reduced to meet our Net Zero targets.",
      explanation: "En la jerga ESG, la contaminación del humo se clasifica formalmente como 'Scope 1 emissions' (emisiones directas) y el objetivo corporativo es 'Net Zero' (Cero Neto)."
    },
    {
      school: "We need to plant trees to fix the pollution.",
      native: "We should purchase verified carbon offsets to mitigate our environmental impact.",
      explanation: "El término corporativo para 'plantar árboles para compensar' es comprar 'carbon offsets' (compensaciones de carbono)."
    }
  ]
};

const envLexicon = [
  {
    term: "Scope 3 Emissions",
    ipa: "/skoʊp θriː ɪˈmɪʃ.ənz/",
    es: "Emisiones de Alcance 3 (Cadena de Valor)",
    category: "Contabilidad de Carbono",
    definition: "Indirect greenhouse gas emissions that occur in a company's value chain, including both upstream and downstream activities (e.g., supplier emissions, business travel, product disposal).",
    collocations: ["calculate Scope 3", "upstream logistics", "value chain"],
    falseFriends: "No es un alcance visual; es la categoría más difícil de rastrear en la contabilidad ambiental, ya que está fuera del control directo de la empresa.",
    nativeUsage: "Scope 3 emissions account for over 80% of our total carbon footprint due to our extensive global supply chain."
  },
  {
    term: "Life Cycle Assessment (LCA)",
    ipa: "/laɪf ˈsaɪ.kəl əˈsɛs.mənt/",
    es: "Análisis de Ciclo de Vida (ACV)",
    category: "Ingeniería Ambiental",
    definition: "A methodology for assessing environmental impacts associated with all the stages of the life cycle of a commercial product, process, or service.",
    collocations: ["cradle to grave", "LCA report", "environmental impact"],
    falseFriends: "No es una evaluación médica; es un estudio ingenieril del impacto de un producto desde la extracción de materia prima hasta la basura.",
    nativeUsage: "The LCA revealed that the manufacturing phase consumes more energy than the actual usage phase of the product."
  },
  {
    term: "Carbon Offset",
    ipa: "/ˈkɑːr.bən ˈɔːf.sɛt/",
    es: "Compensación de Carbono / Bono de Carbono",
    category: "Economía Verde",
    definition: "A reduction or removal of emissions of carbon dioxide or other greenhouse gases made in order to compensate for emissions made elsewhere.",
    collocations: ["purchase carbon offsets", "verified offsets", "reforestation projects"],
    falseFriends: "No es un 'desfase'; es pagar para que alguien más reduzca emisiones y así 'compensar' las tuyas.",
    nativeUsage: "Airlines often allow passengers to buy carbon offsets to neutralize the emissions of their flight."
  },
  {
    term: "Decarbonization",
    ipa: "/diːˌkɑːr.bə.nəˈzeɪ.ʃən/",
    es: "Descarbonización",
    category: "Estrategia Corporativa",
    definition: "The process of reducing or eliminating carbon dioxide emissions from a company's operations, typically by switching to low-carbon energy sources.",
    collocations: ["decarbonization strategy", "energy transition", "Net Zero"],
    falseFriends: "No es quitarle el carbón a un motor viejo; es la reestructuración energética total de una corporación hacia energías limpias.",
    nativeUsage: "Our industrial decarbonization plan involves replacing gas furnaces with electric arc furnaces."
  },
  {
    term: "ESG",
    ipa: "/iː-ɛs-dʒiː/",
    es: "Criterios ASG (Ambiental, Social y Gobernanza)",
    category: "Finanzas y Reportes",
    definition: "Environmental, Social, and Governance. A framework used to assess an organization's business practices and performance on various sustainability and ethical issues.",
    collocations: ["ESG reporting", "ESG rating", "sustainability goals"],
    falseFriends: "Es el acrónimo fundamental para inversores modernos; una mala calificación ESG puede cerrar el acceso a financiamiento.",
    nativeUsage: "Investors are demanding stricter ESG reporting to avoid the financial risks of climate change."
  },
  {
    term: "Net Zero",
    ipa: "/nɛt ˈzɪr.oʊ/",
    es: "Cero Neto (Emisiones)",
    category: "Objetivos Globales",
    definition: "A state in which the greenhouse gases going into the atmosphere are balanced by removal out of the atmosphere.",
    collocations: ["Net Zero targets", "carbon neutrality", "Paris Agreement"],
    falseFriends: "No significa 'cero contaminación' absoluto, sino que las emisiones residuales son eliminadas (compensadas) en igual cantidad.",
    nativeUsage: "The company pledged to achieve Net Zero carbon emissions by 2040 through aggressive renewable energy procurement."
  }
];

const envSocratic = [
  {
    step: 1,
    concept: "GHG Protocol Scopes",
    botQuestion: "Welcome to the ESG Audit! If our company's delivery trucks burn diesel fuel, is that considered a Scope 1, 2, or 3 emission under the GHG Protocol? What about the emissions generated by the airline when our executives fly for business?",
    requiredKeywords: ["scope", "1", "direct", "3", "indirect", "travel", "airline"],
    minKeywords: 3,
    feedbackSuccess: "Perfect! The delivery trucks are owned by the company, making it a direct Scope 1 emission. The business flights are on a third-party airline, making it an indirect Scope 3 emission.",
    feedbackRetry: "Remember, Scope 1 is direct emissions (things the company owns). Scope 3 is indirect emissions in the value chain (things the company doesn't own but pays for, like a flight). Try classifying the delivery trucks vs. the airline travel again."
  },
  {
    step: 2,
    concept: "Carbon Offsets & Decarbonization",
    botQuestion: "If an airline cannot physically run on solar panels yet, how can it achieve a 'Net Zero' target? What financial instrument or mechanism (starts with 'carbon o...') can they purchase to compensate for their jet fuel emissions?",
    requiredKeywords: ["carbon", "offsets", "compensate", "net", "zero", "projects"],
    minKeywords: 2,
    feedbackSuccess: "Exactly! When direct decarbonization is impossible, companies purchase 'carbon offsets' (funding projects like reforestation) to balance their emissions and reach Net Zero.",
    feedbackRetry: "Think about the phrase used when you pay someone else to reduce emissions on your behalf. It's called a 'carbon o_______'. How does this help reach 'Net Zero'?"
  }
];

if (!LXP_COURSES["environmental-sustainability"]) {
  LXP_COURSES["environmental-sustainability"] = {
    id: "environmental-sustainability",
    category: "cat-science",
    title: "Environmental & Sustainability",
    titleES: "Sustentabilidad y Tecnología Ambiental",
    icon: "🌍",
    desc: "Master ESG reporting, Life Cycle Assessments (LCA), and corporate decarbonization strategies.",
    descES: "Domina los reportes ESG, Análisis de Ciclo de Vida (LCA) y estrategias de descarbonización corporativa.",
    modules_required: 1,
    modules: [
      {
        id: "env-m1",
        title: "Carbon Accounting & ESG",
        titleES: "Contabilidad de Carbono y ESG",
        isGoldModel: true,
        readings: [
          {
            id: "env-m1-r1",
            title: "Corporate Sustainability & Decarbonization",
            duration: "10 min",
            content: envReading,
            vocabulary: envLexicon.map(i => ({ en: i.term, es: i.es, definition: i.definition, ipa: i.ipa, collocations: i.collocations }))
          }
        ],
        dialogue: envDialogue,
        lexiconMatrix: envLexicon,
        socraticChallenges: envSocratic,
        quiz: []
      }
    ]
  };
} else {
  LXP_COURSES["environmental-sustainability"].modules[0] = {
    id: "env-m1",
    title: "Carbon Accounting & ESG",
    titleES: "Contabilidad de Carbono y ESG",
    isGoldModel: true,
    readings: [
      {
        id: "env-m1-r1",
        title: "Corporate Sustainability & Decarbonization",
        duration: "10 min",
        content: envReading,
        vocabulary: envLexicon.map(i => ({ en: i.term, es: i.es, definition: i.definition, ipa: i.ipa, collocations: i.collocations }))
      }
    ],
    dialogue: envDialogue,
    lexiconMatrix: envLexicon,
    socraticChallenges: envSocratic,
    quiz: []
  };
}

const header = `/**
 * stemOS LXP Course Content Database
 * ====================================
 * STEM & Specialized English (ESP) — Nearshoring & High-Tech Industry Tracks
 */

var LXP_CATEGORIES = ${JSON.stringify(LXP_CATEGORIES, null, 4)};

var LXP_COURSES = ${JSON.stringify(LXP_COURSES, null, 4)};

if (typeof window !== 'undefined') {
    window.LXP_CATEGORIES = LXP_CATEGORIES;
    window.LXP_COURSES = LXP_COURSES;
}
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { LXP_CATEGORIES, LXP_COURSES };
}
`;

fs.writeFileSync(coursesPath, header, 'utf8');
console.log('Successfully added Environmental module to courses.js');
