/**
 * stemOS Phase A-2: Complete IPA Fix
 * Adds IPA to ALL remaining 491 unique vocabulary terms
 */

const fs = require('fs');
const path = require('path');

const COURSES_PATH = path.join(__dirname, '..', 'content', 'courses.js');

const IPA_FULL = {
  // ==== A ====
  "4680 Cell": "/ˈfɔːr.sɪks.eɪ.ti sɛl/",
  "5-Axis Machining": "/faɪv ˈæk.sɪs məˈʃiː.nɪŋ/",
  "A&P License": "/ˌeɪ.ən ˈpiː ˈlaɪ.səns/",
  "ACID": "/ˈæs.ɪd/",
  "ADAS": "/ˈeɪ.dæs/",
  "AES": "/ˌeɪ.iːˈɛs/",
  "API (Application Programming Interface)": "/ˌeɪ.piːˈaɪ/",
  "AS9100D": "/ˌeɪ.ɛs.naɪn.wʌn.hʌn.drəd.ˈdiː/",
  "ASIL": "/ˈeɪ.sɪl/",
  "ASNT": "/ˌeɪ.ɛs.ɛnˈtiː/",
  "Acceptor": "/əkˈsɛp.tər/",
  "Access Control": "/ˈæk.sɛs kənˈtroʊl/",
  "Active Balancing": "/ˈæk.tɪv ˈbæl.ən.sɪŋ/",
  "Actuator": "/ˈæk.tʃu.eɪ.tər/",
  "Additive Manufacturing": "/ˈæd.ɪ.tɪv ˌmæn.jʊˈfæk.tʃər.ɪŋ/",
  "Adhesive Bonding": "/ədˈhiː.sɪv ˈbɒn.dɪŋ/",
  "Advanced Packaging": "/ədˈvænst ˈpæk.ɪ.dʒɪŋ/",
  "Aerospace Cluster": "/ˈɛr.oʊ.speɪs ˈklʌs.tər/",
  "Agentic AI": "/eɪˈdʒɛn.tɪk ˌeɪˈaɪ/",
  "Agile": "/ˈædʒ.aɪl/",
  "Air Shower": "/ɛr ˈʃaʊ.ər/",
  "All-Wheel Drive (AWD)": "/ˌɔːl wiːl ˈdraɪv/",
  "Anisotropic": "/ˌæn.aɪ.soʊˈtrɒp.ɪk/",
  "Anode": "/ˈæn.oʊd/",
  "Apache Kafka": "/əˈpætʃ.i ˈkæf.kə/",
  "Arc Flash": "/ɑːrk flæʃ/",
  "Architecture": "/ˈɑːr.kɪ.tɛk.tʃər/",
  "Artificial Intelligence (AI)": "/ˌɑːr.tɪˈfɪʃ.əl ɪnˈtɛl.ɪ.dʒəns/",
  "Asynchronous": "/eɪˈsɪŋ.krə.nəs/",
  "Atomic Layer Deposition (ALD)": "/əˈtɒm.ɪk ˈleɪ.ər ˌdɛp.əˈzɪʃ.ən/",
  "Authentication": "/ɔːˌθɛn.tɪˈkeɪ.ʃən/",
  "Autoclave": "/ˈɔː.toʊ.kleɪv/",
  "Automated Guided Vehicle (AGV)": "/ˈɔː.tə.meɪ.tɪd ˈɡaɪ.dɪd ˈviː.ɪ.kəl/",
  "Autonomous Driving": "/ɔːˈtɒn.ə.məs ˈdraɪ.vɪŋ/",
  "Autopilot": "/ˈɔː.toʊ.paɪ.lət/",
  "Availability": "/əˌveɪ.ləˈbɪl.ɪ.ti/",
  "Avionics": "/ˌeɪ.viˈɒn.ɪks/",
  // ==== B ====
  "BGA (Ball Grid Array)": "/ˌbiː.dʒiːˈeɪ/",
  "BMS (Battery Management System)": "/ˌbiː.ɛmˈɛs/",
  "Backup": "/ˈbæk.ʌp/",
  "Bandwidth": "/ˈbænd.wɪdθ/",
  "Batch Processing": "/bætʃ ˈprɒs.ɛs.ɪŋ/",
  "Battery Pack": "/ˈbæt.ər.i pæk/",
  "Battery Preconditioning": "/ˈbæt.ər.i ˌpriː.kənˈdɪʃ.ən.ɪŋ/",
  "Big Data": "/bɪɡ ˈdeɪ.tə/",
  "Binational Megaregion": "/ˌbaɪˈnæʃ.ən.əl ˈmɛɡ.ə.riː.dʒən/",
  "Binning": "/ˈbɪn.ɪŋ/",
  "Biometrics": "/ˌbaɪ.oʊˈmɛt.rɪks/",
  "Blended Braking": "/ˈblɛn.dɪd ˈbreɪ.kɪŋ/",
  "Bluetooth": "/ˈbluː.tuːθ/",
  "Body-in-White": "/ˌbɒd.i.ɪn.ˈwaɪt/",
  "Borescope": "/ˈbɔːr.skoʊp/",
  "Brake Pad": "/breɪk pæd/",
  "Brute Force Attack": "/bruːt fɔːrs əˈtæk/",
  "Build": "/bɪld/",
  "Bulkhead": "/ˈbʊlk.hɛd/",
  "Bunny Suit": "/ˈbʌn.i suːt/",
  "Bus Bar": "/bʌs bɑːr/",
  "Bypass Ratio": "/ˈbaɪ.pæs ˈreɪ.ʃi.oʊ/",
  // ==== C ====
  "CAD (Computer-Aided Design)": "/kæd/",
  "CAN Bus": "/kæn bʌs/",
  "CCS": "/ˌsiː.siːˈɛs/",
  "CD (Continuous Delivery/Deployment)": "/ˌsiːˈdiː/",
  "CFRP": "/ˌsiː.ɛf.ɑːrˈpiː/",
  "CHIPS Act": "/tʃɪps ækt/",
  "CI (Continuous Integration)": "/ˌsiːˈaɪ/",
  "CIA Triad": "/ˌsiː.aɪˈeɪ ˈtraɪ.æd/",
  "CISO": "/ˈsiː.soʊ/",
  "CMC": "/ˌsiː.ɛmˈsiː/",
  "CMM": "/ˌsiː.ɛmˈɛm/",
  "CMOS": "/ˈsiː.mɒs/",
  "CNC (Computer Numerical Control)": "/ˌsiː.ɛnˈsiː/",
  "CPO (Co-Packaged Optics)": "/ˌsiː.piːˈoʊ/",
  "CVE": "/ˌsiː.viːˈiː/",
  "Cache": "/kæʃ/",
  "Caching": "/ˈkæʃ.ɪŋ/",
  "Calendering": "/ˈkæl.ən.dər.ɪŋ/",
  "Capacitor Discharge": "/kəˈpæs.ɪ.tər ˈdɪs.tʃɑːrdʒ/",
  "Capital Expense (CapEx)": "/ˈkæp.ɪ.təl ɪkˈspɛns/",
  "Carbide Tooling": "/ˈkɑːr.baɪd ˈtuː.lɪŋ/",
  "Cathode": "/ˈkæθ.oʊd/",
  "Cell Balancing": "/sɛl ˈbæl.ən.sɪŋ/",
  "Cell-to-Chassis (CTC)": "/sɛl tuː ˈtʃæs.i/",
  "Cell-to-Pack (CTP)": "/sɛl tuː pæk/",
  "Certification": "/ˌsɜːr.tɪ.fɪˈkeɪ.ʃən/",
  "Channel": "/ˈtʃæn.əl/",
  "Charging Curve": "/ˈtʃɑːr.dʒɪŋ kɜːrv/",
  "Charging Infrastructure": "/ˈtʃɑːr.dʒɪŋ ˈɪn.frə.strʌk.tʃər/",
  "Chemical Vapor Deposition (CVD)": "/ˈkɛm.ɪ.kəl ˈveɪ.pər ˌdɛp.əˈzɪʃ.ən/",
  "Chiller": "/ˈtʃɪl.ər/",
  "Chip Packaging": "/tʃɪp ˈpæk.ɪ.dʒɪŋ/",
  "Chiplet": "/ˈtʃɪp.lɪt/",
  "Ciphertext": "/ˈsaɪ.fər.tɛkst/",
  "Circuit Breaker": "/ˈsɜːr.kɪt ˈbreɪ.kər/",
  "Cloud Computing": "/klaʊd kəmˈpjuː.tɪŋ/",
  "Cluster": "/ˈklʌs.tər/",
  "Cobot (Collaborative Robot)": "/ˈkoʊ.bɒt/",
  "Combustion Chamber": "/kəmˈbʌs.tʃən ˈtʃeɪm.bər/",
  "Composite": "/kəmˈpɒz.ɪt/",
  "Compressor": "/kəmˈprɛs.ər/",
  "Confidentiality": "/ˌkɒn.fɪ.dɛn.ʃiˈæl.ɪ.ti/",
  "Configuration Management": "/kənˌfɪɡ.jʊˈreɪ.ʃən ˈmæn.ɪdʒ.mənt/",
  "Connector": "/kəˈnɛk.tər/",
  "Contactor": "/kɒnˈtæk.tər/",
  "Container": "/kənˈteɪ.nər/",
  "Contamination": "/kənˌtæm.ɪˈneɪ.ʃən/",
  "Coolant": "/ˈkuː.lənt/",
  "Corrosion Resistance": "/kəˈroʊ.ʒən rɪˈzɪs.təns/",
  "Coulomb Counting": "/ˈkuː.lɒm ˈkaʊn.tɪŋ/",
  "Counterfeit Part": "/ˈkaʊn.tər.fɪt pɑːrt/",
  "Covalent Bond": "/koʊˈveɪ.lənt bɒnd/",
  "Credential Stuffing": "/krɪˈdɛn.ʃəl ˈstʌf.ɪŋ/",
  "Credentials": "/krɪˈdɛn.ʃəlz/",
  "Creep Resistance": "/kriːp rɪˈzɪs.təns/",
  "Crimp": "/krɪmp/",
  "Cybersecurity": "/ˈsaɪ.bər.sɪˌkjʊr.ɪ.ti/",
  "Cycle Life": "/ˈsaɪ.kəl laɪf/",
  "Cylindrical Cell": "/sɪˈlɪn.drɪ.kəl sɛl/",
  // ==== D ====
  "DC Fast Charging (DCFC)": "/ˌdiːˈsiː fæst ˈtʃɑːr.dʒɪŋ/",
  "DDoS": "/ˌdiː.diː.oʊˈɛs/",
  "DHCP": "/ˌdiː.eɪtʃ.siːˈpiː/",
  "DNS": "/ˌdiː.ɛnˈɛs/",
  "DNSSEC": "/ˌdiː.ɛn.ɛs.ˈsɛk/",
  "DORA Metrics": "/ˈdɔːr.ə ˈmɛt.rɪks/",
  "Data Breach": "/ˈdeɪ.tə briːtʃ/",
  "Data Center": "/ˈdeɪ.tə ˈsɛn.tər/",
  "Data Encryption": "/ˈdeɪ.tə ɪnˈkrɪp.ʃən/",
  "Data Lake": "/ˈdeɪ.tə leɪk/",
  "Data Lakehouse": "/ˈdeɪ.tə ˈleɪk.haʊs/",
  "Data Pipeline": "/ˈdeɪ.tə ˈpaɪp.laɪn/",
  "Data Warehouse": "/ˈdeɪ.tə ˈwɛr.haʊs/",
  "Database": "/ˈdeɪ.tə.beɪs/",
  "Deep Learning": "/diːp ˈlɜːr.nɪŋ/",
  "Defense in Depth": "/dɪˈfɛns ɪn dɛpθ/",
  "Degradation": "/ˌdɛɡ.rəˈdeɪ.ʃən/",
  "Delamination": "/ˌdiː.læm.ɪˈneɪ.ʃən/",
  "Depletion Zone": "/dɪˈpliː.ʃən zoʊn/",
  "Deployment": "/dɪˈplɔɪ.mənt/",
  "Deployment Frequency": "/dɪˈplɔɪ.mənt ˈfriː.kwən.si/",
  "DevOps": "/ˈdɛv.ɒps/",
  "Development": "/dɪˈvɛl.əp.mənt/",
  "Dictionary Attack": "/ˈdɪk.ʃən.ɛr.i əˈtæk/",
  "Die": "/daɪ/",
  "Dielectric Fluid": "/ˌdaɪ.ɪˈlɛk.trɪk ˈfluː.ɪd/",
  "Discontinuity": "/ˌdɪs.kɒn.tɪˈnjuː.ɪ.ti/",
  "Docker": "/ˈdɒk.ər/",
  "Dockerfile": "/ˈdɒk.ər.faɪl/",
  "Document Database": "/ˈdɒk.jʊ.mənt ˈdeɪ.tə.beɪs/",
  "Domain Name": "/doʊˈmeɪn neɪm/",
  "Donor": "/ˈdoʊ.nər/",
  "Doping": "/ˈdoʊ.pɪŋ/",
  "Drain": "/dreɪn/",
  "Dry Battery Electrode": "/draɪ ˈbæt.ər.i ɪˈlɛk.troʊd/",
  "Dry Etching": "/draɪ ˈɛtʃ.ɪŋ/",
  "Duty-Free": "/ˈdjuː.ti friː/",
  "Dynamic IP": "/daɪˈnæm.ɪk ˌaɪˈpiː/",
  "Dyno Testing": "/ˈdaɪ.noʊ ˈtɛs.tɪŋ/",
  // ==== E ====
  "E-Axle": "/ˈiː.æk.səl/",
  "EDM": "/ˌiː.diːˈɛm/",
  "ELT (Extract, Load, Transform)": "/ˌiː.ɛlˈtiː/",
  "ETL (Extract, Transform, Load)": "/ˌiː.tiːˈɛl/",
  "EUV Lithography": "/ˌiː.juːˈviː lɪˈθɒɡ.rə.fi/",
  "EVSE": "/ˌiː.viː.ɛsˈiː/",
  "Eddy Current Testing (ET)": "/ˈɛd.i ˈkʌr.ənt ˈtɛs.tɪŋ/",
  "Edge Computing": "/ɛdʒ kəmˈpjuː.tɪŋ/",
  "Edge Gateway": "/ɛdʒ ˈɡeɪt.weɪ/",
  "Efficiency": "/ɪˈfɪʃ.ən.si/",
  "Elasticity": "/ˌɪ.læsˈtɪs.ɪ.ti/",
  "Electrocution": "/ɪˌlɛk.trəˈkjuː.ʃən/",
  "Electrode": "/ɪˈlɛk.troʊd/",
  "Electrolyte": "/ɪˈlɛk.trə.laɪt/",
  "Electromagnetic Induction": "/ɪˌlɛk.troʊ.mæɡˈnɛt.ɪk ɪnˈdʌk.ʃən/",
  "Electron": "/ɪˈlɛk.trɒn/",
  "Empennage": "/ˌɛm.pɪˈnɑːʒ/",
  "Encrypted": "/ɪnˈkrɪp.tɪd/",
  "Encryption": "/ɪnˈkrɪp.ʃən/",
  "Endpoint": "/ˈɛnd.pɔɪnt/",
  "Energy Density": "/ˈɛn.ər.dʒi ˈdɛn.sɪ.ti/",
  "Epoxy Resin": "/ɪˈpɒk.si ˈrɛz.ɪn/",
  "Equipment Technician": "/ɪˈkwɪp.mənt tɛkˈnɪʃ.ən/",
  "Ethernet": "/ˈiː.θər.nɛt/",
  "Ethical Hacker": "/ˈɛθ.ɪ.kəl ˈhæk.ər/",
  // ==== F ====
  "FMEA": "/ˌɛf.ɛm.iːˈeɪ/",
  "FMS (Flight Management System)": "/ˌɛf.ɛmˈɛs/",
  "Fab (Fabrication Plant)": "/fæb/",
  "Fabless": "/ˈfæb.lɪs/",
  "False Positive": "/fɔːls ˈpɒz.ɪ.tɪv/",
  "Faraday's Law": "/ˈfær.ə.deɪz lɔː/",
  "Fatigue Resistance": "/fəˈtiːɡ rɪˈzɪs.təns/",
  "Fiber Optic": "/ˈfaɪ.bər ˈɒp.tɪk/",
  "FinFET": "/ˈfɪn.fɛt/",
  "Final Assembly Line (FAL)": "/ˈfaɪ.nəl əˈsɛm.bli laɪn/",
  "Fine-tuning": "/ˈfaɪn ˌtjuː.nɪŋ/",
  "Firewall": "/ˈfaɪ.ər.wɔːl/",
  "Firmware": "/ˈfɜːrm.wɛr/",
  "First Article Inspection (FAI)": "/fɜːrst ˈɑːr.tɪ.kəl ɪnˈspɛk.ʃən/",
  "Flow-Down": "/ˈfloʊ.daʊn/",
  "Formation": "/fɔːrˈmeɪ.ʃən/",
  "Forward Bias": "/ˈfɔːr.wərd ˈbaɪ.əs/",
  "Foundry": "/ˈfaʊn.dri/",
  "Frame": "/freɪm/",
  "Friction Braking": "/ˈfrɪk.ʃən ˈbreɪ.kɪŋ/",
  "Friction Stir Welding": "/ˈfrɪk.ʃən stɜːr ˈwɛl.dɪŋ/",
  "Full-duplex": "/fʊl ˈdjuː.plɛks/",
  "Fuselage": "/ˈfjuː.zəl.ɑːʒ/",
  // ==== G ====
  "G-code": "/ˈdʒiː.koʊd/",
  "GAA": "/ˌdʒiː.eɪˈeɪ/",
  "Gate": "/ɡeɪt/",
  "Gateway": "/ˈɡeɪt.weɪ/",
  "Generator Mode": "/ˈdʒɛn.ə.reɪ.tər moʊd/",
  "Gigafactory": "/ˈɡɪɡ.ə.fæk.tər.i/",
  "GitOps": "/ˈɡɪt.ɒps/",
  "Glass Cockpit": "/ɡlæs ˈkɒk.pɪt/",
  "Gown Room": "/ɡaʊn ruːm/",
  "Gowning Protocol": "/ˈɡaʊ.nɪŋ ˈproʊ.tə.kɒl/",
  "Grain Boundary": "/ɡreɪn ˈbaʊn.dri/",
  "Graph Database": "/ɡræf ˈdeɪ.tə.beɪs/",
  // ==== H ====
  "HBM (High Bandwidth Memory)": "/ˌeɪtʃ.biːˈɛm/",
  "HTTP / HTTPS": "/ˌeɪtʃ.tiː.tiːˈpiː/",
  "Hardware": "/ˈhɑːrd.wɛr/",
  "Hash Function": "/hæʃ ˈfʌŋk.ʃən/",
  "Heat Dissipation": "/hiːt ˌdɪs.ɪˈpeɪ.ʃən/",
  "Heat Lot": "/hiːt lɒt/",
  "Heat Pump": "/hiːt pʌmp/",
  "Hi-Lok Fastener": "/haɪ lɒk ˈfæs.ən.ər/",
  "High Voltage (HV)": "/haɪ ˈvoʊl.tɪdʒ/",
  "High-NA EUV": "/haɪ ˌɛn.ˈeɪ ˌiː.juːˈviː/",
  "Hole": "/hoʊl/",
  "Horizontal Scaling": "/ˌhɒr.ɪˈzɒn.təl ˈskeɪ.lɪŋ/",
  "Hypervisor": "/ˈhaɪ.pər.vaɪ.zər/",
  // ==== I ====
  "IAM (Identity and Access Management)": "/ˌaɪ.eɪˈɛm/",
  "IATF 16949": "/ˌaɪ.eɪ.tiːˈɛf/",
  "IDM": "/ˌaɪ.diːˈɛm/",
  "IDS": "/ˌaɪ.diːˈɛs/",
  "IFE (In-Flight Entertainment)": "/ˌaɪ.ɛfˈiː/",
  "IIoT (Industrial Internet of Things)": "/ˌaɪ.aɪ.oʊˈtiː/",
  "IP Address": "/ˌaɪˈpiː əˈdrɛs/",
  "IPC/WHMA-A-620": "/ˌaɪ.piːˈsiː/",
  "IPS": "/ˌaɪ.piːˈɛs/",
  "IPv4": "/ˌaɪ.piːˈviː.fɔːr/",
  "IPv6": "/ˌaɪ.piːˈviː.sɪks/",
  "ISO 26262": "/ˌaɪ.ɛs.ˈoʊ/",
  "ISP": "/ˌaɪ.ɛsˈpiː/",
  "IaaS (Infrastructure as a Service)": "/ˈaɪ.æs/",
  "Image": "/ˈɪm.ɪdʒ/",
  "Incident Response": "/ˈɪn.sɪ.dənt rɪˈspɒns/",
  "Induction Motor": "/ɪnˈdʌk.ʃən ˈmoʊ.tər/",
  "Industry 4.0": "/ˈɪn.dəs.tri fɔːr pɔɪnt ˈoʊ/",
  "Information Technology (IT)": "/ˌɪn.fərˈmeɪ.ʃən tɛkˈnɒl.ə.dʒi/",
  "Infrastructure as Code (IaC)": "/ˈɪn.frə.strʌk.tʃər æz koʊd/",
  "Integrity": "/ɪnˈtɛɡ.rɪ.ti/",
  "Intercalation": "/ɪnˌtɜːr.kəˈleɪ.ʃən/",
  "Internal Combustion Engine (ICE)": "/ɪnˈtɜːr.nəl kəmˈbʌs.tʃən ˈɛn.dʒɪn/",
  "Investment Casting": "/ɪnˈvɛst.mənt ˈkæs.tɪŋ/",
  "Ion Implantation": "/ˈaɪ.ɒn ˌɪm.plænˈteɪ.ʃən/",
  "Isotropic": "/ˌaɪ.soʊˈtrɒp.ɪk/",
  // ==== K ====
  "Kernel": "/ˈkɜːr.nəl/",
  "Key-Value Store": "/kiː ˈvæl.juː stɔːr/",
  "Kinetic Energy": "/kɪˈnɛt.ɪk ˈɛn.ər.dʒi/",
  "Kubernetes (K8s)": "/ˌkuː.bərˈnɛt.iːz/",
  // ==== L ====
  "LAN (Local Area Network)": "/læn/",
  "LFP (Lithium Iron Phosphate)": "/ˌɛl.ɛfˈpiː/",
  "LLM (Large Language Model)": "/ˌɛl.ɛlˈɛm/",
  "LPWAN": "/ˌɛl.piː.dʌb.əl.juːˈeɪ.ɛn/",
  "Laser Tracker": "/ˈleɪ.zər ˈtræk.ər/",
  "Laser Welding": "/ˈleɪ.zər ˈwɛl.dɪŋ/",
  "Latency": "/ˈleɪ.tən.si/",
  "Lay-up": "/ˈleɪ.ʌp/",
  "Leakage Current": "/ˈliː.kɪdʒ ˈkʌr.ənt/",
  "Least Privilege": "/liːst ˈprɪv.əl.ɪdʒ/",
  "Level 1 Charging": "/ˈlɛv.əl wʌn ˈtʃɑːr.dʒɪŋ/",
  "Level 2 Charging": "/ˈlɛv.əl tuː ˈtʃɑːr.dʒɪŋ/",
  "Liquid Penetrant (PT)": "/ˈlɪk.wɪd ˈpɛn.ɪ.trənt/",
  "Lithium Plating": "/ˈlɪθ.i.əm ˈpleɪ.tɪŋ/",
  "Lithium-Ion Battery": "/ˈlɪθ.i.əm ˈaɪ.ɒn ˈbæt.ər.i/",
  "Load Balancing": "/loʊd ˈbæl.ən.sɪŋ/",
  "Lockout/Tagout (LOTO)": "/ˈlɒk.aʊt ˈtæɡ.aʊt/",
  "Lorentz Force": "/ˈlɒr.ənts fɔːrs/",
  // ==== M ====
  "MAC Address": "/mæk əˈdrɛs/",
  "MAN (Metropolitan Area Network)": "/mæn/",
  "MEA (More Electric Aircraft)": "/ˌɛm.iːˈeɪ/",
  "MES (Manufacturing Execution System)": "/mɛs/",
  "MFA": "/ˌɛm.ɛfˈeɪ/",
  "MFA (Multi-Factor Authentication)": "/ˌɛm.ɛfˈeɪ/",
  "MOSFET": "/ˈmɒs.fɛt/",
  "MRO": "/ˌɛm.ɑːrˈoʊ/",
  "Machine Learning (ML)": "/məˈʃiːn ˈlɜːr.nɪŋ/",
  "Malware": "/ˈmæl.wɛr/",
  "Manufacturing Specialist": "/ˌmæn.jʊˈfæk.tʃər.ɪŋ ˈspɛʃ.əl.ɪst/",
  "Marriage (assembly)": "/ˈmær.ɪdʒ/",
  "Mass Production": "/mæs prəˈdʌk.ʃən/",
  "Mbps / Gbps": "/ˈmɛɡ.ə.bɪts pər ˈsɛk.ənd/",
  "Microcontroller": "/ˌmaɪ.kroʊ.kənˈtroʊ.lər/",
  "Milling": "/ˈmɪl.ɪŋ/",
  "Misconfiguration": "/ˌmɪs.kənˌfɪɡ.jʊˈreɪ.ʃən/",
  "Module": "/ˈmɒdʒ.uːl/",
  "Monolith": "/ˈmɒn.ə.lɪθ/",
  "Moore's Law": "/mʊrz lɔː/",
  "Multimeter": "/ˈmʌl.tɪˌmiː.tər/",
  "Mutual Authentication": "/ˈmjuː.tʃu.əl ɔːˌθɛn.tɪˈkeɪ.ʃən/",
  // ==== N ====
  "N-Type": "/ˈɛn taɪp/",
  "NACS / SAE J3400": "/næks/",
  "NADCAP": "/ˈnæd.kæp/",
  "NAS 410": "/næs/",
  "NAT": "/næt/",
  "NCR (Non-Conformance Report)": "/ˌɛn.siːˈɑːr/",
  "NDT (Non-Destructive Testing)": "/ˌɛn.diːˈtiː/",
  "NMC (Nickel Manganese Cobalt)": "/ˌɛn.ɛmˈsiː/",
  "NOM": "/nɒm/",
  "Nearshoring": "/ˈnɪr.ʃɔːr.ɪŋ/",
  "Neural Network": "/ˈnjʊr.əl ˈnɛt.wɜːrk/",
  "NoSQL": "/ˌnoʊˈsiː.kwəl/",
  "Non-Conformance (NC)": "/ˌnɒn.kənˈfɔːr.məns/",
  // ==== O ====
  "OSAT": "/ˈoʊ.sæt/",
  "OSI Model": "/ˌoʊ.ɛs.ˈaɪ ˈmɒd.əl/",
  "OT Security": "/ˌoʊˈtiː sɪˈkjʊr.ɪ.ti/",
  "OWASP Top 10": "/ˈoʊ.wɒsp/",
  "On-Premises": "/ɒn ˈprɛm.ɪ.sɪz/",
  "One-Pedal Driving": "/wʌn ˈpɛd.əl ˈdraɪ.vɪŋ/",
  "Operating System": "/ˈɒp.ər.eɪ.tɪŋ ˈsɪs.təm/",
  "Orchestration": "/ˌɔːr.kɪˈstreɪ.ʃən/",
  "Over-fetching": "/ˈoʊ.vər ˈfɛtʃ.ɪŋ/",
  "Overlay Accuracy": "/ˈoʊ.vər.leɪ ˈæk.jʊr.ə.si/",
  // ==== P ====
  "P-N Junction": "/ˌpiːˈɛn ˈdʒʌŋk.ʃən/",
  "P-Type": "/ˈpiː taɪp/",
  "PAN (Personal Area Network)": "/pæn/",
  "PLC (Programmable Logic Controller)": "/ˌpiː.ɛlˈsiː/",
  "PMSM": "/ˌpiː.ɛm.ɛsˈɛm/",
  "PPE": "/ˌpiː.piːˈiː/",
  "PaaS (Platform as a Service)": "/pæs/",
  "Packing Efficiency": "/ˈpæk.ɪŋ ɪˈfɪʃ.ən.si/",
  "Passive Balancing": "/ˈpæs.ɪv ˈbæl.ən.sɪŋ/",
  "Passphrase": "/ˈpæs.freɪz/",
  "Password Manager": "/ˈpæs.wɜːrd ˈmæn.ɪ.dʒər/",
  "Patch": "/pætʃ/",
  "Pay-as-you-go": "/ˈpeɪ.æz.juːˈɡoʊ/",
  "Penetration Testing": "/ˌpɛn.ɪˈtreɪ.ʃən ˈtɛs.tɪŋ/",
  "Phased Array": "/feɪzd əˈreɪ/",
  "Phishing": "/ˈfɪʃ.ɪŋ/",
  "Photomask": "/ˈfoʊ.toʊ.mæsk/",
  "Photoresist": "/ˈfoʊ.toʊ.rɪ.zɪst/",
  "Physical Vapor Deposition (PVD)": "/ˈfɪz.ɪ.kəl ˈveɪ.pər ˌdɛp.əˈzɪʃ.ən/",
  "Pipeline": "/ˈpaɪp.laɪn/",
  "Plaintext": "/ˈpleɪn.tɛkst/",
  "Pod": "/pɒd/",
  "Polyglot Persistence": "/ˈpɒl.i.ɡlɒt pərˈsɪs.təns/",
  "Porosity": "/pɔːˈrɒs.ɪ.ti/",
  "Pouch Cell": "/paʊtʃ sɛl/",
  "Power Packaging": "/ˈpaʊ.ər ˈpæk.ɪ.dʒɪŋ/",
  "Powertrain": "/ˈpaʊ.ər.treɪn/",
  "Predictive Maintenance": "/prɪˈdɪk.tɪv ˈmeɪn.tən.əns/",
  "Prismatic Cell": "/prɪzˈmæt.ɪk sɛl/",
  "Private Key": "/ˈpraɪ.vɪt kiː/",
  "Probe Testing": "/proʊb ˈtɛs.tɪŋ/",
  "Process Engineer": "/ˈprɒs.ɛs ˌɛn.dʒɪˈnɪr/",
  "Process Node": "/ˈprɒs.ɛs noʊd/",
  "Prompt Engineering": "/prɒmpt ˌɛn.dʒɪˈnɪr.ɪŋ/",
  "Public Key": "/ˈpʌb.lɪk kiː/",
  "Pylon": "/ˈpaɪ.lɒn/",
  // ==== Q ====
  "Quality Control": "/ˈkwɒl.ɪ.ti kənˈtroʊl/",
  "Query": "/ˈkwɪr.i/",
  // ==== R ====
  "RAG": "/ræɡ/",
  "RPM": "/ˌɑːr.piːˈɛm/",
  "Radiator": "/ˈreɪ.di.eɪ.tər/",
  "Radiographic Testing (RT)": "/ˌreɪ.di.oʊˈɡræf.ɪk ˈtɛs.tɪŋ/",
  "Range": "/reɪndʒ/",
  "Ransomware": "/ˈræn.sʌm.wɛr/",
  "Rare Earth Elements": "/rɛr ɜːrθ ˈɛl.ɪ.mənts/",
  "Reduction Gear": "/rɪˈdʌk.ʃən ɡɪr/",
  "Refactor": "/riːˈfæk.tər/",
  "Reflective Mirror": "/rɪˈflɛk.tɪv ˈmɪr.ər/",
  "Regen Limit": "/ˈriː.dʒɛn ˈlɪm.ɪt/",
  "Regenerative Braking": "/rɪˈdʒɛn.ər.ə.tɪv ˈbreɪ.kɪŋ/",
  "Regional Content": "/ˈriː.dʒən.əl ˈkɒn.tɛnt/",
  "Remediate": "/rɪˈmiː.di.eɪt/",
  "Repository": "/rɪˈpɒz.ɪ.tɔːr.i/",
  "Requirements": "/rɪˈkwaɪr.mənts/",
  "Rescue Sheet": "/ˈrɛs.kjuː ʃiːt/",
  "Retrospective": "/ˌrɛt.roʊˈspɛk.tɪv/",
  "Rivet": "/ˈrɪv.ɪt/",
  "Rolling Update": "/ˈroʊ.lɪŋ ˈʌp.deɪt/",
  "Rotor": "/ˈroʊ.tər/",
  "Routing": "/ˈruː.tɪŋ/",
  // ==== S ====
  "SCADA": "/ˈskeɪ.dɑː/",
  "SDLC": "/ˌɛs.diː.ɛlˈsiː/",
  "SIEM": "/sɪm/",
  "SOC (Security Operations Center)": "/sɒk/",
  "SOP": "/ˌɛs.oʊˈpiː/",
  "SOP (Standard Operating Procedure)": "/ˌɛs.oʊˈpiː/",
  "SPC": "/ˌɛs.piːˈsiː/",
  "SQL": "/ˌɛs.kjuːˈɛl/",
  "SSO (Single Sign-On)": "/ˌɛs.ɛsˈoʊ/",
  "SaaS (Software as a Service)": "/sæs/",
  "Scalability": "/ˌskeɪ.ləˈbɪl.ɪ.ti/",
  "Schema": "/ˈskiː.mə/",
  "Schema-on-Read": "/ˈskiː.mə ɒn riːd/",
  "Scrum": "/skrʌm/",
  "Self-Attention": "/sɛlf əˈtɛn.ʃən/",
  "Self-healing": "/sɛlf ˈhiː.lɪŋ/",
  "Separator": "/ˈsɛp.ə.reɪ.tər/",
  "Server": "/ˈsɜːr.vər/",
  "Service Disconnect": "/ˈsɜːr.vɪs ˌdɪs.kəˈnɛkt/",
  "Session": "/ˈsɛʃ.ən/",
  "Shared Responsibility Model": "/ʃɛrd rɪˌspɒn.sɪˈbɪl.ɪ.ti ˈmɒd.əl/",
  "Short Circuit": "/ʃɔːrt ˈsɜːr.kɪt/",
  "Silicon Photonics": "/ˈsɪl.ɪ.kən foʊˈtɒn.ɪks/",
  "Single Crystal": "/ˈsɪŋ.ɡəl ˈkrɪs.təl/",
  "Single-Crystal Casting": "/ˈsɪŋ.ɡəl ˈkrɪs.təl ˈkæs.tɪŋ/",
  "Slurry": "/ˈslʌr.i/",
  "Smartshoring": "/ˈsmɑːrt.ʃɔːr.ɪŋ/",
  "Social Engineering": "/ˈsoʊ.ʃəl ˌɛn.dʒɪˈnɪr.ɪŋ/",
  "Software": "/ˈsɒf.wɛr/",
  "Solder Ball": "/ˈsɒd.ər bɔːl/",
  "Solid-State Battery": "/ˈsɒl.ɪd steɪt ˈbæt.ər.i/",
  "Source": "/sɔːrs/",
  "Spear Phishing": "/spɪr ˈfɪʃ.ɪŋ/",
  "Special Process": "/ˈspɛʃ.əl ˈprɒs.ɛs/",
  "Spectrum": "/ˈspɛk.trəm/",
  "Spin Coating": "/spɪn ˈkoʊ.tɪŋ/",
  "Spoofing": "/ˈspuː.fɪŋ/",
  "Sprint": "/sprɪnt/",
  "Staging Environment": "/ˈsteɪ.dʒɪŋ ɪnˈvaɪ.rən.mənt/",
  "State of Charge (SoC)": "/steɪt əv tʃɑːrdʒ/",
  "State of Health (SoH)": "/steɪt əv hɛlθ/",
  "Static IP": "/ˈstæt.ɪk ˌaɪˈpiː/",
  "Statistical Process Control (SPC)": "/stəˈtɪs.tɪ.kəl ˈprɒs.ɛs kənˈtroʊl/",
  "Stator": "/ˈsteɪ.tər/",
  "Stop-Ship": "/stɒp ʃɪp/",
  "Stream Processing": "/striːm ˈprɒs.ɛs.ɪŋ/",
  "Strength-to-Weight Ratio": "/strɛŋθ tuː weɪt ˈreɪ.ʃi.oʊ/",
  "Stress Analysis": "/strɛs əˈnæl.ɪ.sɪs/",
  "Stringer": "/ˈstrɪŋ.ər/",
  "Superalloy": "/ˈsuː.pər.æl.ɔɪ/",
  "Supercharger": "/ˈsuː.pər.tʃɑːr.dʒər/",
  "Supervised Learning": "/ˈsuː.pər.vaɪzd ˈlɜːr.nɪŋ/",
  "Supply Chain": "/səˈplaɪ tʃeɪn/",
  "Surface Roughness (Ra)": "/ˈsɜːr.fɪs ˈrʌf.nəs/",
  "Swelling": "/ˈswɛl.ɪŋ/",
  "Synchronous": "/ˈsɪŋ.krə.nəs/",
  // ==== T ====
  "TCAS": "/ˈtiː.kæs/",
  "TCP": "/ˌtiː.siːˈpiː/",
  "TLS/SSL": "/ˌtiː.ɛl.ˈɛs/",
  "TOTP": "/ˈtiː.oʊ.tiː.piː/",
  "Tabless Electrode": "/ˈtæb.lɪs ɪˈlɛk.troʊd/",
  "Technical English": "/ˈtɛk.nɪ.kəl ˈɪŋ.ɡlɪʃ/",
  "Terraform": "/ˈtɛr.ə.fɔːrm/",
  "Thermal Barrier Coating (TBC)": "/ˈθɜːr.məl ˈbær.i.ər ˈkoʊ.tɪŋ/",
  "Thermal Management": "/ˈθɜːr.məl ˈmæn.ɪdʒ.mənt/",
  "Thermal Runaway": "/ˈθɜːr.məl ˈrʌn.ə.weɪ/",
  "Tier 1 Supplier": "/tɪr wʌn səˈplaɪ.ər/",
  "Tin": "/tɪn/",
  "Titanium": "/taɪˈteɪ.ni.əm/",
  "Topology": "/təˈpɒl.ə.dʒi/",
  "Torque": "/tɔːrk/",
  "Torque Vectoring": "/tɔːrk ˈvɛk.tər.ɪŋ/",
  "Transducer": "/trænzˈdjuː.sər/",
  "Transformer": "/trænsˈfɔːr.mər/",
  "Transistor": "/trænˈzɪs.tər/",
  "Trojan": "/ˈtroʊ.dʒən/",
  "Turbine Blade": "/ˈtɜːr.baɪn bleɪd/",
  "Turbofan": "/ˈtɜːr.boʊ.fæn/",
  "Turning": "/ˈtɜːr.nɪŋ/",
  // ==== U ====
  "UDP": "/ˌjuː.diːˈpiː/",
  "UNAQ": "/ˈjuː.næk/",
  "USMCA": "/ˌjuː.ɛs.ɛmˈsiː.eɪ/",
  "UV Exposure": "/ˌjuːˈviː ɪkˈspoʊ.ʒər/",
  "Ultrasonic Testing (UT)": "/ˌʌl.trə.ˈsɒn.ɪk ˈtɛs.tɪŋ/",
  "Unit Test": "/ˈjuː.nɪt tɛst/",
  // ==== V ====
  "VPN": "/ˌviː.piːˈɛn/",
  "VPN (Virtual Private Network)": "/ˌviː.piːˈɛn/",
  "Vault": "/vɔːlt/",
  "Vehicle-to-Grid (V2G)": "/ˈviː.ɪ.kəl tuː ɡrɪd/",
  "Ventricular Fibrillation": "/vɛnˈtrɪk.jʊ.lər ˌfɪb.rɪˈleɪ.ʃən/",
  "Version Control": "/ˈvɜːr.ʒən kənˈtroʊl/",
  "Virtual Machine (VM)": "/ˈvɜːr.tʃu.əl məˈʃiːn/",
  "Virus": "/ˈvaɪ.rəs/",
  "Vulnerability": "/ˌvʌl.nər.əˈbɪl.ɪ.ti/",
  // ==== W ====
  "WAN (Wide Area Network)": "/wæn/",
  "Wafer Map": "/ˈweɪ.fər mæp/",
  "Waterfall": "/ˈwɔː.tər.fɔːl/",
  "Wavelength": "/ˈweɪv.lɛŋθ/",
  "Well-Architected Framework": "/wɛl ˈɑːr.kɪ.tɛk.tɪd ˈfreɪm.wɜːrk/",
  "Wet Etching": "/wɛt ˈɛtʃ.ɪŋ/",
  "Wire Bonding": "/waɪr ˈbɒn.dɪŋ/",
  "Wire Harness": "/waɪr ˈhɑːr.nɪs/",
  "Work Instruction": "/wɜːrk ɪnˈstrʌk.ʃən/",
  "Worm": "/wɜːrm/",
  // ==== Y-Z ====
  "Yield": "/jiːld/",
  "Zero Trust": "/ˈzɪr.oʊ trʌst/",
  "fcBGA (Flip-Chip Ball Grid Array)": "/ˌɛf.siːˌbiː.dʒiːˈeɪ/",
  "kW (Kilowatt)": "/ˈkɪl.ə.wɒt/",
};

const content = fs.readFileSync(COURSES_PATH, 'utf-8');
eval(content);

let fixCount = 0;
let stillMissing = [];

for (const trackId of Object.keys(LXP_COURSES)) {
  const track = LXP_COURSES[trackId];
  for (const mod of (track.modules || [])) {
    for (const reading of (mod.readings || [])) {
      for (const vocab of (reading.vocabulary || [])) {
        if (!vocab.ipa && vocab.en) {
          const ipaVal = IPA_FULL[vocab.en];
          if (ipaVal) {
            vocab.ipa = ipaVal;
            fixCount++;
          } else {
            stillMissing.push(vocab.en);
          }
        }
      }
    }
  }
}

console.log(`IPA fixes applied: ${fixCount}`);
if (stillMissing.length > 0) {
  const unique = [...new Set(stillMissing)].sort();
  console.log(`\nStill missing: ${unique.length}`);
  unique.forEach(t => console.log(`  - ${t}`));
}

let output = `/**\n * stemOS LXP Course Content Database\n * ====================================\n * STEM & Specialized English (ESP) — Nearshoring & High-Tech Industry Tracks\n */\n\nvar LXP_CATEGORIES = ${JSON.stringify(LXP_CATEGORIES, null, 4)};\n\nvar LXP_COURSES = ${JSON.stringify(LXP_COURSES, null, 4)};\n`;

fs.writeFileSync(COURSES_PATH, output, 'utf-8');
console.log(`\n✅ Written. File size: ${(Buffer.byteLength(output) / 1024 / 1024).toFixed(2)} MB`);
